import { NextPage } from 'next'

import Head from 'next/head'
import Image from 'next/image'
import { FiSearch, FiBell, FiChevronDown } from 'react-icons/fi'
import DoughnutChart from '../components/Chart/DoughnutChart'
import LineChart from '../components/Chart/LineChart'
import VerticalBarChart from '../components/Chart/VerticalBarChart'
import Info from '../components/Info'
import Notification from '../components/Notification'
import Sidebar from '../components/Sidebar'
import Widget from '../components/Widget'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Teamify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto   xl:my-12 bg-gray-50 md:bg-white xl:rounded-3xl">
        <div className="flex">
          <div className="-ml-[250px] w-[250px] md:ml-0  lg:w-[290px] xl:rounded-tl-3xl xl:rounded-bl-3xl overflow-hidden">
            <Sidebar />
          </div>
          <div className="flex-1 w-screen h-screen xl:h-auto overflow-scroll xl:overflow-hidden">
            <main className=" py-8 px-4 lg:px-10">
              {/* header */}
              <div className="flex mb-8 lg:mb-12">
                <div className="flex-1">
                  <h1 className="text-lg md:text-2xl font-bold">
                    Good Morning Anima
                  </h1>
                  <p className="text-sm">Hope you have a good day</p>
                </div>

                <div className="flex items-center">
                  <button className="text-gray-500">
                    <FiSearch size={24} />
                  </button>

                  <button className="ml-2 lg:ml-10 text-gray-500">
                    <FiBell size={24} />
                  </button>

                  <div className="ml-2 lg:ml-10 w-12 h-12 rounded-full">
                    <Image
                      src={'/user.png'}
                      width={48}
                      height={48}
                      alt="user"
                    />
                  </div>

                  <button className="ml-4 text-gray-500">
                    <FiChevronDown size={16} />
                  </button>
                </div>
              </div>

              {/* content */}
              <div className="space-y-4 lg:grid lg:space-y-0 lg:grid-cols-2 lg:gap-3 xl:grid-cols-3 xl:gap-5">
                {/* widget 1 */}
                <Widget>
                  <Widget.Header>
                    <Widget.HeaderLeft>
                      <Widget.Title>Team Strength</Widget.Title>
                    </Widget.HeaderLeft>
                  </Widget.Header>
                  <Widget.Body>
                    <VerticalBarChart />
                  </Widget.Body>
                </Widget>

                {/* widget 2 */}
                <Widget>
                  <Widget.Header>
                    <Widget.HeaderLeft>
                      <Widget.Title>Employees</Widget.Title>
                    </Widget.HeaderLeft>
                    <Widget.HeaderRight>
                      <Widget.Date>Aug 25-Sept 25</Widget.Date>
                    </Widget.HeaderRight>
                  </Widget.Header>
                  <Widget.Body>
                    <DoughnutChart />
                  </Widget.Body>
                </Widget>

                {/* widget 3 */}
                <div className="col-span-2">
                  <Widget>
                    <Widget.Header>
                      <Widget.HeaderLeft>
                        <Widget.Title>Project Delivered</Widget.Title>
                      </Widget.HeaderLeft>
                      <Widget.HeaderRight>
                        <Widget.Label
                          circleClass="bg-orange-500"
                          labelClass="mr-12"
                        >
                          Achieved
                        </Widget.Label>
                        <Widget.Label circleClass="bg-indigo-500">
                          Target
                        </Widget.Label>
                      </Widget.HeaderRight>
                    </Widget.Header>
                    <Widget.Body>
                      <LineChart />
                    </Widget.Body>
                  </Widget>
                </div>

                {/* widget 4 */}
                <div className="xl:row-start-1 xl:col-start-3 space-y-4">
                  <Info
                    variant="orange"
                    title="Top 10"
                    subtitle="Position in Dribble"
                    info="20% increase from last week"
                  />
                  <Info
                    variant="indigo"
                    title="26"
                    subtitle="New employees onboarded"
                    info="15% Increase from Last Month"
                  />
                  <Info
                    variant="blue"
                    title="500"
                    subtitle="New Clients Approached"
                    info="5% Increase from Last Week"
                  />
                </div>

                {/* widget-5 */}
                <div>
                  {/* widget-5__header */}
                  <div className="flex mb-7">
                    <h2 className="lg:text-lg font-bold flex-1">
                      Notification
                    </h2>
                    <a
                      href="#"
                      className="text-indigo-500 text-sm font-semibold"
                    >
                      View All
                    </a>
                  </div>

                  {/* widget-5__list */}
                  <div className="space-y-4">
                    <Notification
                      src="/notif-1.png"
                      user="Ellie"
                      title="Ellie joined team developers"
                      date="04 April, 2021 | 04:00 PM"
                    />
                    <Notification
                      src="/notif-2.png"
                      user="Jenny"
                      title="Jenny joined team HR"
                      date="04 April, 2021 | 04:00 PM"
                    />
                    <Notification
                      src="/notif-3.png"
                      user="Adam"
                      title="Adam got employee of the month"
                      date="03 April, 2021 | 02:00 PM"
                    />
                    <Notification
                      src="/notif-4.png"
                      user="Robert"
                      title="Robert joined team design"
                      date="02 April, 2021 | 02:00 PM"
                    />
                    <Notification
                      src="/notif-5.png"
                      user="Jack"
                      title="Jack joined team design"
                      date="01 April, 2021 | 21:00 PM"
                    />
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
